---
all:
  children:
    arista:
      hosts:
        arista-1:
          ansible_host: 192.168.161.10
          ansible_network_os: eos
          ansible_become: yes
          ansible_become_method: enable
          ansible_user: arista
          ansible_password: arista
          ansible_become_pass: arista
        arista-2:
          ansible_host: 192.168.161.11
          ansible_network_os: eos
          ansible_become: yes
          ansible_become_method: enable
          ansible_user: arista
          ansible_password: arista
          ansible_become_pass: arista