---
all:
  children:
    arista_veos:
      hosts:
        veos_1:
          ansible_host: 192.168.161.10
          ansible_network_os: eos
          ansible_become: yes
          ansible_become_method: enable
          #ansible_user: "{{ username }}"
          #ansible_password: "{{ password }}"
          #ansible_become_pass: "{{ enable_password }}"
          ansible_user: arista
          ansible_password: arista
          ansible_become_pass: arista
        veos_2:
          ansible_host: 192.168.161.11
          ansible_network_os: eos
          ansible_become: yes
          ansible_become_method: enable
          #ansible_user: "{{ username }}"
          #ansible_password: "{{ password }}"
          #ansible_become_pass: "{{ enable_password }}"
          ansible_user: arista
          ansible_password: arista
          ansible_become_pass: arista
    cisco_ios:
      hosts:
        ios_1:
          ansible_host: 192.168.161.20
          ansible_network_os: ios
          ansible_become: yes
          ansible_become_method: enable
          ansible_user: cisco-ios
          ansible_password: ciscoios
          ansible_become_pass: ciscoios
        ios_2:
          ansible_host: 192.168.161.21
          ansible_network_os: ios
          ansible_become: yes
          ansible_become_method: enable
          ansible_user: cisco-ios
          ansible_password: ciscoios
          ansible_become_pass: ciscoios
    cisco_nxos:
      hosts:
        nxos-1:
          ansible_host: 192.168.161.30
          ansible_network_os: nxos
          ansible_become: yes
          ansible_become_method: enable
          ansible_user: cisco-nxos
          ansible_password: Cisconxos1
          ansible_become_pass: Cisconxos1
#        nxos-2:
#          ansible_host: 192.168.161.31
#          ansible_network_os: nxos
#          ansible_become: yes
#          ansible_become_method: enable
#          ansible_user: cisco-nxos
#          ansible_password: cisconxos
#          ansible_become_pass: cisconxos