---
all:
  children:
    arista-veos:
      hosts:
        veos-1:
          ansible_host: 192.168.161.10
          ansible_network_os: eos
          ansible_become: yes
          ansible_become_method: enable
          ansible_user: arista
          ansible_password: arista
          ansible_become_pass: arista
        veos-2:
          ansible_host: 192.168.161.11
          ansible_network_os: eos
          ansible_become: yes
          ansible_become_method: enable
          ansible_user: arista
          ansible_password: arista
          ansible_become_pass: arista
    cisco-ios:
      hosts:
        ios-1:
          ansible_host: 192.168.161.20
          ansible_network_os: ios
          ansible_become: yes
          ansible_become_method: enable
          ansible_user: cisco-ios
          ansible_password: ciscoios
          ansible_become_pass: ciscoios
        ios-2:
          ansible_host: 192.168.161.21
          ansible_network_os: ios
          ansible_become: yes
          ansible_become_method: enable
          ansible_user: cisco-ios
          ansible_password: ciscoios
          ansible_become_pass: ciscoios
    cisco-nxos:
      hosts:
        nxos-1:
          ansible_host: 192.168.161.30
          ansible_network_os: nxos
          ansible_become: yes
          ansible_become_method: enable
          ansible_user: cisco-nxos
          ansible_password: cisconxos
          ansible_become_pass: cisconxos
        nxos-2:
          ansible_host: 192.168.161.31
          ansible_network_os: nxos
          ansible_become: yes
          ansible_become_method: enable
          ansible_user: cisco-nxos
          ansible_password: cisconxos
          ansible_become_pass: cisconxos