---
platform: ios
ansible_python_interpreter: /Users/fitzadd/Documents/NetDevOps/arista-af/bin/python

provider_cli:
  host: "{{ ansible_host }}"
  transport: cli
  use_ssl: yes
  username: "cisco-ios"
  password: "ciscoios"
  authorize: yes
  auth_pass: "ciscoios"
  timeout: 60

date_time_now: "{{lookup('pipe','date \"+%d-%m-%Y\"')}}"