---
# Take Cisco IOS Backups
- name: Cisco IOS Config Backup
  ios_command:
    commands:
      - show running-config
  register: config_output
  #when: "'cisco_ios' in group_names"

- name: Copy Backup to File
  copy:
    content: "{{ config_output.stdout[0] }}"
    dest: "/Users/fitzadd/Documents/NetDevOps/GitHub/device-config-backup/device_backups/{{ ansible_host }}_{{date_time_now}}_running-config.txt"
  #when: "'cisco_ios' in group_names"