- name: Playbook
  #hosts: cisco_ios:arista_veos
  hosts: all
  connection: network_cli
  gather_facts: False

  roles:
  - config-backups

# Use this vars_prompt for Radius
#  vars_prompt:
#    - name: "username"
#      prompt: "Username"
#      private: no
#    - name: "password"
#      prompt: "Password"
#      private: yes
#    - name: "enable_password"
#      prompt: "Enable Password"
#      private: yes