---
- name: Arista vEOS Playbook
  hosts: arista_veos
  connection: network_cli
  gather_facts: False

  roles:
  - veos

- name: Cisco IOS Playbook
  hosts: cisco_ios
  connection: network_cli
  gather_facts: False

  roles:
  - ios
  
- name: Cisco NXOS Playbook
  hosts: cisco_nxos
  connection: network_cli
  gather_facts: False

  roles:
  - nxos





# Use this vars_prompt for Radius
#  vars_prompt:
#    - name: "username"
#      prompt: "Username"
#      private: no
#    - name: "password"
#      prompt: "Password"
#      private: yes
#    - name: "enable_password"
#      prompt: "Enable Password"
#      private: yes